@startuml

    interface GraphDatabase [[GraphDatabase.html]] {
        {abstract} +g(): GraphTraversalSource
        {abstract} +writeGraph(String): void
        {abstract} +loadGraph(File): void
        {abstract} +fromVertex(Vertex, Class<T>): T
        {abstract} +addVertex(Object): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
