@startuml

    class HoughLinesLineDetector [[HoughLinesLineDetector.html]] {
        +HoughLinesLineDetector()
        +HoughLinesLineDetector(boolean, double, double, int, double, double)
        +detect(Mat): Collection<Line>
        +getRho(): double
        +setRho(double): void
        +getTheta(): double
        +setTheta(double): void
        +getThreshold(): int
        +setThreshold(int): void
        +getMinLineLength(): double
        +setMinLineLength(double): void
        +getMaxLineGap(): double
        +setMaxLineGap(double): void
        +isProbabilistic(): boolean
        +setProbabilistic(boolean): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
