@startuml

    class DebugTools [[DebugTools.html]] {
        +DebugTools(String, String)
        +output(Mat, String): void
        +output(Mat, Collection<Line>, String, Scalar): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
