@startuml

    namespace nl.vaneijndhoven.dukes.bosshogg {

        class BossHogg [[BossHogg.html]] {
            +start(): void
        }

        class io.vertx.rxjava.core.AbstractVerticle
        io.vertx.rxjava.core.AbstractVerticle <|-- BossHogg

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
