@startuml

    class StartLightDetectionApp <<deprecated>> [[StartLightDetectionApp.html]] {
        + --start-- (Stage): void
        {static} + --main-- (String[]): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
