@startuml

    class ImageUtils [[ImageUtils.html]] {
        {static} +mat2Image(Mat): Image
        {static} +releaseImages(Mat[]): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
