@startuml

    namespace nl.vaneijndhoven.objects.stoppingzone {

        class ZoneEndBoundary [[ZoneEndBoundary.html]] {
            {static} +DEFAULT_ANGLE: double
            {static} +DEFAULT_TOLERANCE: double
            +ZoneEndBoundary()
            +ZoneEndBoundary(double, double, boolean)
        }

        class ZoneStartBoundary [[ZoneStartBoundary.html]] {
            {static} +DEFAULT_ANGLE: double
            {static} +DEFAULT_TOLERANCE: double
            +ZoneStartBoundary()
            +ZoneStartBoundary(double, double, boolean)
            +boundary(Collection<Line>): Optional<Line>
        }

        class nl.vaneijndhoven.objects.Boundary
        nl.vaneijndhoven.objects.Boundary <|-- ZoneEndBoundary

        nl.vaneijndhoven.objects.Boundary <|-- ZoneStartBoundary

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
