# use 16.04
dist: xenial
# this is a java project using maven
language: java
# we'll get java 11 or higher if we don't do this
jdk:
  - openjdk8
# switch off gpg handling
# clean is mandatory to get opencv jar integrated
install: mvn clean install -Dgpg.skip=true
# We need GraphViz to get uml diagrams with javadoc 
before_install:
- "sudo apt-get install graphviz"
# we need to install opencv 
# by compiling from source (takes some 15 minutes ...)
# if you comment this out some tests will fail 
# so you might want to add -D skipTests above
- "scripts/opencvubuntu"
