# use 16.04
dist: xenial
# this is a java project using maven
language: java
# switch off gpg handling
# clean is mandatory to get opencv jar integrated
install: mvn clean install -Dgpg.skip=true
# We need GraphViz to get uml diagrams with javadoc 
before_install:
- "sudo apt-get install graphviz"
# we need to install opencv
- "scripts/opencvubuntu"
