@startuml

    class TestAction [[TestAction.html]] {
        {static} +debug: boolean
        {static} +TIME_OUT: int
        +check(Observable<JsonObject>, int, String[]): void
        +testStraightLaneNavigator(): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
