@startuml

    class DefaultStartLightDetector [[DefaultStartLightDetector.html]] {
        +DefaultStartLightDetector()
        +DefaultStartLightDetector(int, int, int, int, int, int)
        +DefaultStartLightDetector(DefaultStartLightDetector.Config)
        +detect(Mat): StartLight
        +withDebug(DebugTools): DefaultStartLightDetector
        +getFrame(): Mat
        +withImageCollector(ImageCollector): DefaultStartLightDetector
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
