@startuml

    class Line.Vector [[Line.Vector.html]] {
        +Vector(double, double)
        +calculate(Point2D, double): Point2D
        +calculateX(double): double
        +calculateY(double): double
        {static} +forY(double): Line.Vector
        {static} +forX(double): Line.Vector
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
