@startuml

    interface Point3D [[Point3D.html]] {
        {abstract} +getZ(): double
        {abstract} +distance(Point3D): double
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
