@startuml

    class TestAction [[TestAction.html]] {
        {static} +debug: boolean
        +check(JsonObject, String[]): void
        +testAction(): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
