@startuml

    class Polygon [[Polygon.html]] {
        {static} +debug: boolean
        +Polygon(Point2D[])
        +init(Point2D[]): void
        +getPoints(): List<Point2D>
        +getPointsClockwise(): List<Point2D>
        +getPointsCounterClockwise(): List<Point2D>
        {static} +square(Point2D, Point2D): Polygon
        +intersect(Line): Set<Point2D>
        +edges(): List<Line>
        +shoelace(): double
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
