@startuml

    enum DukesVerticle.Status [[DukesVerticle.Status.html]] {
        {static} +created
        {static} +started
        {static} +stopped
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
