@startuml

    namespace nl.vaneijndhoven.daisy {

        class Daisy [[Daisy.html]] {
            {static} +MAT: Mat
            {static} +BIRDS_EYE: Mat
            {static} +CANNY_IMG: byte[]
            +start(): void
        }

        class StartLightDetector [[StartLightDetector.html]] {
            +StartLightDetector()
            +StartLightDetector(int, int, int, int, int, int)
            +StartLightDetector(StartLightDetector.Config)
            +detect(Mat): StartLight
            +withDebug(DebugTools): StartLightDetector
            +getFrame(): Mat
            +withImageCollector(ImageCollector): StartLightDetector
        }

        class nl.vaneijndhoven.daisy.StartLightDetector.Config [[StartLightDetector.Config.html]] {
            +getHueStart(): double
            +setHueStart(double): void
            +getHueStop(): double
            +setHueStop(double): void
            +getSaturationStart(): double
            +setSaturationStart(double): void
            +getSaturationStop(): double
            +setSaturationStop(double): void
            +getValueStart(): double
            +setValueStart(double): void
            +getValueStop(): double
            +setValueStop(double): void
        }

        class LaneDetector [[LaneDetector.html]] {
            {static} +DEFAULT_LANE_BOUNDARY_ANGLE: double
            {static} +DEFAULT_LANE_BOUNDARY_TOLERANCE: double
            {static} +DEFAULT_CANNY_THRESHOLD_1: double
            {static} +DEFAULT_CANNY_THRESHOLD_2: double
            {static} +DEFAULT_LINE_DETECT_RHO: int
            {static} +DEFAULT_LINE_DETECT_THETA: double
            {static} +DEFAULT_LINE_DETECT_THRESHOLD: double
            {static} +DEFAULT_LINE_DETECT_MIN_LINE_LENGTH: double
            {static} +DEFAULT_LINE_DETECT_MAX_LINE_GAP: double
            +LaneDetector(CannyEdgeDetector.Config, ProbabilisticHoughLinesLineDetector.Config, CameraMatrix, ImageCollector)
            +detect(Mat): Map<String, Object>
            +performLaneDetection(Mat): Map<String, Object>
            +setCannyConfig(CannyEdgeDetector.Config): void
            +setLineDetectorConfig(ProbabilisticHoughLinesLineDetector.Config): void
            +setCollector(ImageCollector): void
        }

        class ImageFetcher [[ImageFetcher.html]] {
            +ImageFetcher(String)
            +fetch(): Mat
            +toObservable(): Observable<Mat>
        }

        class io.vertx.rxjava.core.AbstractVerticle
        io.vertx.rxjava.core.AbstractVerticle <|-- Daisy

        StartLightDetector +-- nl.vaneijndhoven.daisy.StartLightDetector.Config

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
