@startuml

    class Line [[Line.html]] {
        +Line(double[])
        +Line(Point2D, Point2D)
        +length(): double
        +angleRad(): double
        +angleDeg(): double
        +getPoint1(): Point2D
        +getPoint2(): Point2D
        {static} +average(Line[]): Line
        {static} +average(Collection<Line>): Line
        +isLeftOfLine(Point2D): boolean
        +isRightOfLine(Point2D): boolean
        +existsOnLine(Point2D): boolean
        +bottomMost(): Point2D
        +leftMost(): Point2D
        +rightMost(): Point2D
        +topMost(): Point2D
        +pointAt(double): Point2D
        +width(): double
        +height(): double
        +intersect(Line): Optional<Point2D>
        +distance(Point2D): double
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
