@startuml

    class StoppingZone [[StoppingZone.html]] {
        +StoppingZone(Optional<Line>, Optional<Line>)
        +getEntrance(): Optional<Line>
        +getExit(): Optional<Line>
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
