@startuml

    class Daisy [[Daisy.html]] {
        {static} +MAT: Mat
        {static} +BIRDS_EYE: Mat
        {static} +CANNY_IMG: byte[]
        +start(): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
