@startuml

    namespace nl.vaneijndhoven.opencv.startlightdetection {

        class DefaultStartLightDetector [[DefaultStartLightDetector.html]] {
            +DefaultStartLightDetector()
            +DefaultStartLightDetector(int, int, int, int, int, int)
            +DefaultStartLightDetector(DefaultStartLightDetector.Config)
            +detect(Image): StartLight
            +getFrame(): Mat
            +withImageCollector(ImageCollector): DefaultStartLightDetector
        }

        class nl.vaneijndhoven.opencv.startlightdetection.DefaultStartLightDetector.Config [[DefaultStartLightDetector.Config.html]] {
            +getHueStart(): double
            +setHueStart(double): void
            +getHueStop(): double
            +setHueStop(double): void
            +getSaturationStart(): double
            +setSaturationStart(double): void
            +getSaturationStop(): double
            +setSaturationStop(double): void
            +getValueStart(): double
            +setValueStart(double): void
            +getValueStop(): double
            +setValueStop(double): void
        }

        interface org.rcdukes.detectors.StartLightDetector {
            {abstract} +detect(Image): StartLight
            {abstract} +withImageCollector(ImageCollector): StartLightDetector
        }
        org.rcdukes.detectors.StartLightDetector <|.. DefaultStartLightDetector

        DefaultStartLightDetector +-- nl.vaneijndhoven.opencv.startlightdetection.DefaultStartLightDetector.Config

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
