@startuml

    namespace com.bitplan.rc.roi {

        class TestROI [[TestROI.html]] {
            {static} +debug: boolean
            +isTravis(): boolean
            +testNativeLibrary(): void
            +testROI(): void
        }

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
