@startuml

    class TestStraightLaneNavigator [[TestStraightLaneNavigator.html]] {
        {static} +debug: boolean
        {static} +setUp(): void
        +getLdr(int, int, Double, Double, Double): LaneDetectionResult
        +testStraightLaneNavigator(): void
        +testFromJson(): void
        +testFromVideo(): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
