@startuml

    namespace org.rcdukes.webcontrol {

        class WebControl [[WebControl.html]] {
            +start(): void
        }

        abstract class org.rcdukes.common.DukesVerticle
        org.rcdukes.common.DukesVerticle <|-- WebControl

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
