@startuml

    class SteeringMap [[SteeringMap.html]] {
        {static} +WHEEL_CENTER: int
        {static} +WHEEL_STEP_SIZE: int
        {static} +WHEEL_MAX_LEFT: int
        {static} +WHEEL_MAX_RIGHT: int
        +center(): int
        +stepSize(): int
        +maxLeft(): int
        +maxRight(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
