@startuml

    interface ExceptionHandler [[ExceptionHandler.html]] {
        {abstract} +handle(Throwable, String): void
        {abstract} +handle(Throwable): void
        {abstract} +warn(String): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
