@startuml

    class Car [[Car.html]] {
        +Car(Engine, Steering)
        +stop(): void
        +turn(double): void
        +drive(double): void
        +getEngine(): Engine
        +getSteering(): Steering
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
