@startuml

    class Steering [[Steering.html]] {
        +Steering(SteeringMap)
        +center(): void
        +forceCenter(): void
        {static} +setWheelPosition(int): void
        +getSteeringMap(): SteeringMap
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
