@startuml

    namespace nl.vaneijndhoven.opencv.mapper {

        class PointMapper [[PointMapper.html]] {
            {static} +toPoint(Point2D): Point
        }

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
