@startuml

    class NativeLibrary [[NativeLibrary.html]] {
        {static} #nativeLibPath: File
        {static} #currentLibraryPath: String[]
        {static} +getNativeLibPath(): File
        {static} +setNativeLibPath(File): void
        {static} +getCurrentLibraryPath(): String[]
        {static} +addLibraryPath(String): void
        {static} +getLibraryFileName(): String
        {static} +getNativeLib(): File
        {static} +load(): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
