@startuml

    enum OsCheck.OSType [[OsCheck.OSType.html]] {
        {static} +Windows
        {static} +MacOS
        {static} +Linux
        {static} +Other
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
