@startuml

    class OsCheck [[OsCheck.html]] {
        {static} #detectedOS: OsCheck.OSType
        {static} +getOperatingSystemType(): OsCheck.OSType
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
