@startuml

    class MJpegHandler [[MJpegHandler.html]] {
        +MJpegHandler(String)
        +MJpegHandler()
        +getInputStream(): BodyDeferringAsyncHandler.BodyDeferringInputStream
        +open(int): MJpegDecoder
        +close(): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
