@startuml

    enum Events [[Events.html]] {
        {static} +STREAMADDED
        {static} +CANNYCONFIG
        {static} +HOUGHLINESCONFIG
        {static} +LANEDETECTION
        {static} +STARTLIGHTDETECTION
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
