@startuml

    class CannyEdgeDetector.Config [[CannyEdgeDetector.Config.html]] {
        +setThreshold1(double): void
        +setThreshold2(double): void
        +getThreshold1(): double
        +getThreshold2(): double
        +getApertureSize(): int
        +getL2gradient(): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
