@startuml

    namespace nl.vaneijndhoven.opencv.objectdetection {

        class LineExtractor [[LineExtractor.html]] {
            +LineExtractor(EdgeDetector, LineDetector)
            +extract(Mat): Collection<Line>
        }

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
