@startuml

    interface EngineMap [[EngineMap.html]] {
        {abstract} +neutral(): int
        {abstract} +stepSize(): int
        {abstract} +minReverse(): int
        {abstract} +maxReverse(): int
        {abstract} +minForward(): int
        {abstract} +maxForward(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
