@startuml

    namespace nl.vaneijndhoven.dukes.roi {

        class RightField [[RightField.html]] {
            +RightField(double)
        }

        class RegionOfInterest [[RegionOfInterest.html]] {
            +RegionOfInterest(double, double, double, double)
            +getxFraction(): double
            +getyFraction(): double
            +getWidthFraction(): double
            +getHeightFraction(): double
            +roi(Size): Rect
            +region(Mat): Mat
        }

        class NearField [[NearField.html]] {
            +NearField(double)
        }

        class LeftField [[LeftField.html]] {
            +LeftField(double)
        }

        class FarField [[FarField.html]] {
            +FarField(double)
        }

        RegionOfInterest <|-- RightField

        RegionOfInterest <|-- NearField

        RegionOfInterest <|-- LeftField

        RegionOfInterest <|-- FarField

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
