@startuml

    class StoppingZoneOrientation [[StoppingZoneOrientation.html]] {
        +StoppingZoneOrientation(StoppingZone, Lane, ViewPort)
        +determineDistanceToStoppingZone(): double
        +determineDistanceToStoppingZoneEnd(): double
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
