@startuml

    class TestImageCollector [[TestImageCollector.html]] {
        {static} +setup(): void
        +testImageCollector(): void
        +testImageCollectorObservable(): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
