@startuml

    class TestHoughLinesDetector [[TestHoughLinesDetector.html]] {
        +getCanny(Mat, double, double, int): Mat
        +getTestImage2(): Mat
        +testProbabilisticHoughLinesDetector(): void
        +testHoughLinesDetector(): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
