@startuml

    class ServoCommandDummy [[ServoCommandDummy.html]] {
        +resetLog(): void
        +setServo(int, int): void
        +g(): GraphTraversalSource
        +showLog(): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
