@startuml

    class Boundary [[Boundary.html]] {
        +Boundary(LineFilter)
        +boundary(Collection<Line>): Optional<Line>
        +candidates(Collection<Line>): Collection<Line>
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
