@startuml

    class SimulatorImageFetcher [[SimulatorImageFetcher.html]] {
        {static} +debug: boolean
        {static} #LOG: Logger
        #receiveSimulatorImage(Message<String>): void
        +toObservable(): Observable<Image>
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
