@startuml

    class ActionVerticle [[ActionVerticle.html]] {
        +start(): void
        {static} +emergencyStopCommand(): JsonObject
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
