@startuml

    class ZoneEndBoundary [[ZoneEndBoundary.html]] {
        {static} +DEFAULT_ANGLE: double
        {static} +DEFAULT_TOLERANCE: double
        +ZoneEndBoundary()
        +ZoneEndBoundary(double, double, boolean)
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
