@startuml

    class LaneDetectionController <<deprecated>> [[LaneDetectionController.html]] {
        {static} + --DEFAULT_LANE_BOUNDARY_ANGLE-- : double
        {static} + --DEFAULT_LANE_BOUNDARY_TOLERANCE-- : double
        {static} + --DEFAULT_CANNY_THRESHOLD_1-- : double
        {static} + --DEFAULT_CANNY_THRESHOLD_2-- : double
        {static} + --DEFAULT_LINE_DETECT_RHO-- : int
        {static} + --DEFAULT_LINE_DETECT_THETA-- : double
        {static} + --DEFAULT_LINE_DETECT_THRESHOLD-- : double
        {static} + --DEFAULT_LINE_DETECT_MIN_LINE_LENGTH-- : double
        {static} + --DEFAULT_LINE_DETECT_MAX_LINE_GAP-- : double
        + --LaneDetectionController-- (Vertx)
        + --performLaneDetection-- (Mat, CannyEdgeDetector.Config, ProbabilisticHoughLinesLineDetector.Config, ImageCollector): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
