@startuml

    namespace org.rcdukes.watchdog {

        class TestAsync [[TestAsync.html]] {
            +testWatchDog(): void
            +setUp(TestContext): void
            +testAsync(TestContext): void
        }

        class TestWatchDog [[TestWatchDog.html]] {
            +testWatchDog(): void
        }

        class WatchDog [[WatchDog.html]] {
            {static} #HEARTBEAT_INTERVAL_MS: int
            {static} #MAX_MISSED_BEATS: int
            #subscription: Subscription
            +WatchDog(Car)
            +start(): void
        }

        abstract class org.rcdukes.common.DukesVerticle
        org.rcdukes.common.DukesVerticle <|-- WatchDog

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
