@startuml

    class CannyEdgeDetector [[CannyEdgeDetector.html]] {
        +CannyEdgeDetector()
        +CannyEdgeDetector(double, double, int, boolean)
        +getThreshold1(): double
        +setThreshold1(double): void
        +getThreshold2(): double
        +setThreshold2(double): void
        +getApertureSize(): int
        +setApertureSize(int): void
        +isL2gradient(): boolean
        +setL2gradient(boolean): void
        +detect(Mat): Mat
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
