@startuml

    class TestImageFetcher [[TestImageFetcher.html]] {
        {static} +testSource: String
        {static} +getTestImageFetcher(): ImageFetcher
        +testImageFetcher(): void
        +testImageFetcherObservable(): void
        +testImageFetcherObservableSample(): void
        +testStaticImage(): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
