@startuml

    namespace org.rcdukes.remotecar {

        class TestRemoteCar [[TestRemoteCar.html]] {
            +testRemoteCar(): void
            +testRemoteCarCommandLine(): void
        }

        class TestSuite [[TestSuite.html]] {
            {static} +isTravis(): boolean
        }

        class RemoteCar [[RemoteCar.html]] {
            #parser: CmdLineParser
            #debug: boolean
            +start(): void
            +parseArguments(String[]): void
            +mainInstance(String[]): void
            {static} +main(String[]): void
        }

        abstract class org.rcdukes.common.DukesVerticle
        org.rcdukes.common.DukesVerticle <|-- RemoteCar

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
