@startuml

    class ImageFetcher [[ImageFetcher.html]] {
        +ImageFetcher(String)
        +fetch(): Mat
        +toObservable(): Observable<Mat>
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
