@startuml

    class TestGraphDatabase.Person [[TestGraphDatabase.Person.html]] {
        +name: String
        +age: int
        +Person()
        +Person(String, int)
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
