package org.rcdukes.common;

/**
 *  relevant Events
 */
public enum Events {
    CAMERA_CONFIG_UPDATE,
    CANNY_CONFIG_UPDATE,
    HOUGH_CONFIG_UPDATE,
    CAMERA_MATRIX_UPDATE,
    START_LANE_DETECTION,
    LANE_DETECTED,
    START_STARTLIGHT_DETECTION,
    STARTLIGHT_DETECTED,
    START_DRAG_NAVIGATION,
    STOP_NAVIGATION, START_RECORDING, STOP_RECORDING, PHOTO_SHOOT, 
    SIMULATOR_IMAGE, REQUEST_CONFIG, START_CAR
}
