package org.rcdukes.common;

/**
 *  relevant Events
 */
public enum Events {
    CAMERA_CONFIG_UPDATE,
    CANNY_CONFIG_UPDATE,
    HOUGH_CONFIG_UPDATE,
    CAMERA_MATRIX_UPDATE,
    START_LANE_DETECTION,
    START_STARTLIGHT_DETECTION,
    START_DRAG_NAVIGATION,
    STOP_NAVIGATION, START_RECORDING, STOP_RECORDING
}
