package org.rcdukes.common;

/**
 *  relevant Events
 */
public enum Events {
    STREAMADDED,
    CANNYCONFIG,
    HOUGHLINESCONFIG,
    LANEDETECTION,
    STARTLIGHTDETECTION,
    START_DRAG_NAVIGATION,
    STOP_NAVIGATION, START_RECORDING, STOP_RECORDING
}
